image: golang:alpine

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

build:
  tags:
    - docker-with-registry
  stage: build
  before_script:
    - apk add -U make
    - mkdir -p /go/src/git.liquidweb.com/masre/liquidweb-go
    - cp -r $CI_PROJECT_DIR /go/src/git.liquidweb.com/masre/liquidweb-go
  script:
    - make build
